/**
 * Irregular French verb dictionary. Maps infinitive -> full VerbInfo.
 * Generated by scripts/buildIrregularVerbs.mjs from french-verbs-lefff conjugations.json.
 * Do not edit by hand; run the script and commit the output.
 */
import type { VerbInfo } from "./verbInfo";

import irregularVerbsData from "./irregularVerbsData.json";

export const irregularVerbs: Record<string, VerbInfo> =
  irregularVerbsData as unknown as Record<string, VerbInfo>;
